version: "3.5"

networks:
  flashsale:
    name: flashsale

services:
  api01: &api
    build: .
    hostname: api01
    env_file: .env
    depends_on:
      - db
    networks:
      - flashsale
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "85MB"

  api02:
    <<: *api
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - flashsale
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash_sale
    ports:
      - "5432:5432"
    volumes:
      - ./.config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >-
      postgres
      -c checkpoint_timeout=600
      -c max_wal_size=4096
      -c shared_buffers=128MB
      -c synchronous_commit=off
      -c max_connections=150
    networks:
      - flashsale
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "350MB"
